[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
camunda_connector_rs = "0.3.0"
axum = "0.8.4"
inventory = "0.3.20"
serde = { version = "1.0.219", features = ["derive"] }
tokio = {  version = "1.47.1" , features = ["full"]}
serde_json = "1.0.142"
