[template]

[placeholders]
app_description = { type = "string", prompt = "Project description?", default = "My awesome connector" }
license = { type = "string", prompt = "License (MIT/Apache-2.0/Unlicense)?", default = "MIT" }